/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ResetPasswordImport } from './routes/reset-password'
import { Route as RecoverPasswordImport } from './routes/recover-password'
import { Route as LoginImport } from './routes/login'
import { Route as DesktopAgentBindImport } from './routes/desktop-agent-bind'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutTasksImport } from './routes/_layout/tasks'
import { Route as LayoutSettingsImport } from './routes/_layout/settings'
import { Route as LayoutReportsImport } from './routes/_layout/reports'
import { Route as LayoutProjectsImport } from './routes/_layout/projects'
import { Route as LayoutItemsImport } from './routes/_layout/items'
import { Route as LayoutDisciplineHelpImport } from './routes/_layout/discipline-help'
import { Route as LayoutDashboardsImport } from './routes/_layout/dashboards'
import { Route as LayoutCalendarImport } from './routes/_layout/calendar'
import { Route as LayoutBlocksImport } from './routes/_layout/blocks'
import { Route as LayoutAdminImport } from './routes/_layout/admin'
import { Route as LayoutTasksTaskIdImport } from './routes/_layout/tasks.$taskId'
import { Route as LayoutProjectsProjectIdImport } from './routes/_layout/projects.$projectId'

// Create/Update Routes

const ResetPasswordRoute = ResetPasswordImport.update({
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const RecoverPasswordRoute = RecoverPasswordImport.update({
  path: '/recover-password',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const DesktopAgentBindRoute = DesktopAgentBindImport.update({
  path: '/desktop-agent-bind',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutTasksRoute = LayoutTasksImport.update({
  path: '/tasks',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSettingsRoute = LayoutSettingsImport.update({
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutReportsRoute = LayoutReportsImport.update({
  path: '/reports',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutProjectsRoute = LayoutProjectsImport.update({
  path: '/projects',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutItemsRoute = LayoutItemsImport.update({
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutDisciplineHelpRoute = LayoutDisciplineHelpImport.update({
  path: '/discipline-help',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutDashboardsRoute = LayoutDashboardsImport.update({
  path: '/dashboards',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutCalendarRoute = LayoutCalendarImport.update({
  path: '/calendar',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutBlocksRoute = LayoutBlocksImport.update({
  path: '/blocks',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAdminRoute = LayoutAdminImport.update({
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutTasksTaskIdRoute = LayoutTasksTaskIdImport.update({
  path: '/$taskId',
  getParentRoute: () => LayoutTasksRoute,
} as any)

const LayoutProjectsProjectIdRoute = LayoutProjectsProjectIdImport.update({
  path: '/$projectId',
  getParentRoute: () => LayoutProjectsRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/desktop-agent-bind': {
      preLoaderRoute: typeof DesktopAgentBindImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/recover-password': {
      preLoaderRoute: typeof RecoverPasswordImport
      parentRoute: typeof rootRoute
    }
    '/reset-password': {
      preLoaderRoute: typeof ResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/_layout/admin': {
      preLoaderRoute: typeof LayoutAdminImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/blocks': {
      preLoaderRoute: typeof LayoutBlocksImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/calendar': {
      preLoaderRoute: typeof LayoutCalendarImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/dashboards': {
      preLoaderRoute: typeof LayoutDashboardsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/discipline-help': {
      preLoaderRoute: typeof LayoutDisciplineHelpImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/items': {
      preLoaderRoute: typeof LayoutItemsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/projects': {
      preLoaderRoute: typeof LayoutProjectsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/reports': {
      preLoaderRoute: typeof LayoutReportsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/settings': {
      preLoaderRoute: typeof LayoutSettingsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/tasks': {
      preLoaderRoute: typeof LayoutTasksImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/projects/$projectId': {
      preLoaderRoute: typeof LayoutProjectsProjectIdImport
      parentRoute: typeof LayoutProjectsImport
    }
    '/_layout/tasks/$taskId': {
      preLoaderRoute: typeof LayoutTasksTaskIdImport
      parentRoute: typeof LayoutTasksImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LayoutRoute.addChildren([
    LayoutAdminRoute,
    LayoutBlocksRoute,
    LayoutCalendarRoute,
    LayoutDashboardsRoute,
    LayoutDisciplineHelpRoute,
    LayoutItemsRoute,
    LayoutProjectsRoute.addChildren([LayoutProjectsProjectIdRoute]),
    LayoutReportsRoute,
    LayoutSettingsRoute,
    LayoutTasksRoute.addChildren([LayoutTasksTaskIdRoute]),
    LayoutIndexRoute,
  ]),
  DesktopAgentBindRoute,
  LoginRoute,
  RecoverPasswordRoute,
  ResetPasswordRoute,
])

/* prettier-ignore-end */
