PERMISSIONS: list[tuple[str, str]] = [
    ("read_organization", "Read Organization"),
    ("create_organization", "Create Organization"),
    ("update_organization", "Update Organization"),
    ("delete_organization", "Delete Organization"),
    ("create_project", "Create Project"),
    ("read_project_basic", "Read Project Basic"),
    ("read_project_full", "Read Project Full"),
    ("update_project", "Update Project"),
    ("delete_project", "Delete Project"),
    ("read_role", "Read Role"),
    ("manage_role", "Manage Role"),
    ("update_self", "Update Self"),
    ("create_user", "Create User"),
    ("read_user_basic", "Read User Basic"),
    ("read_user_full", "Read User Full"),
    ("update_user", "Update User"),
    ("delete_user", "Delete User"),
    ("create_group", "Create Group"),
    ("read_group", "Read Group"),
    ("update_group", "Update Group"),
    ("delete_group", "Delete Group"),
    ("low_level_admin_read", "Low-level Admin Read"),
    ("low_level_admin_write", "Low-level Admin Write"),
    ("task_update", "Обновление задачи"),
    ("task_delete", "Удаление задачи"),
    ("task_create_links", "Создание связей задач"),
    ("task_commands_without_notifications", "Применять команды без уведомлений"),
    ("watchers_update", "Обновление списка наблюдателей"),
    ("attachment_add", "Добавление вложения"),
    ("attachment_update", "Обновление вложения"),
    ("attachment_delete", "Удаление вложения"),
    ("task_comment_create", "Создание комментария к задаче"),
    ("task_comment_read", "Чтение комментария к задаче"),
    ("task_comment_update", "Обновление комментария к задаче"),
    ("task_comment_delete", "Удаление комментария к задаче"),
    ("tag_saved_search_create", "Создание тега или сохраненного поиска"),
    ("tag_saved_search_update", "Изменение тега или сохраненного поиска"),
    ("tag_saved_search_delete", "Удаление тега или сохраненного поиска"),
    ("share_custom_view", "Share Custom View"),
    ("work_item_read", "Чтение единицы работы"),
    ("work_item_update", "Обновление единицы работы"),
    ("work_item_create", "Создание единицы работы"),
    ("report_read", "Чтение отчета"),
    ("issue_read", "Чтение задачи"),
    ("issue_private_fields_read", "Чтение закрытых полей задач"),
    ("issue_create", "Создание задачи"),
    ("watchers_read", "Просмотр списка наблюдателей"),
    ("voters_read", "Просмотр списка проголосовавших пользователей"),
    ("foreign_comment_update", "Обновление чужого комментария к задаче"),
    (
        "foreign_comment_delete_permanent",
        "Удаление чужого комментария и окончательное удаление комментария",
    ),
    ("foreign_work_item_update", "Обновление единицы работы другого пользователя"),
    ("foreign_work_item_create", "Создание единицы работы другого пользователя"),
    ("report_create", "Создание отчета"),
    ("report_share", "Поделиться отчетом"),
    ("article_read", "Чтение статьи"),
    ("issue_private_fields_update", "Обновление закрытых полей задачи"),
    ("visibility_constraints_bypass", "Подавление ограничений видимости"),
    ("article_create", "Создание статьи"),
    ("article_update", "Обновление статьи"),
    ("article_delete", "Удаление статьи"),
    ("article_comment_read", "Чтение комментария к статье"),
    ("article_comment_create", "Создание комментария к статье"),
    ("article_comment_update", "Обновление комментария к статье"),
    ("article_comment_delete", "Удаление комментария к статье"),
]

ROLE_TO_PERMISSIONS: dict[str, list[str]] = {
    "system_admin": [permission_key for permission_key, _ in PERMISSIONS],
    "reader": [
        "read_project_basic",
        "read_project_full",
        "issue_read",
        "task_comment_read",
        "attachment_add",
        "report_read",
    ],
    "contributor": [
        "read_project_basic",
        "read_project_full",
        "issue_read",
        "issue_create",
        "task_update",
        "task_comment_read",
        "task_comment_create",
        "task_comment_update",
        "attachment_add",
        "attachment_update",
        "report_read",
    ],
    "project_admin": [
        "read_project_basic",
        "read_project_full",
        "update_project",
        "read_group",
        "update_group",
        "issue_read",
        "issue_create",
        "task_update",
        "task_delete",
        "task_comment_read",
        "task_comment_create",
        "task_comment_update",
        "task_comment_delete",
        "attachment_add",
        "attachment_update",
        "attachment_delete",
        "report_read",
        "report_create",
        "report_share",
    ],
}

ROLE_TITLES: dict[str, str] = {
    "system_admin": "System Admin",
    "reader": "Читатель",
    "contributor": "Контрибьютор",
    "project_admin": "Администратор проекта",
}

ROLE_DESCRIPTIONS: dict[str, str] = {
    "system_admin": "Системный администратор",
    "reader": "Читатель",
    "contributor": "Контрибьютор",
    "project_admin": "Администратор проекта",
}

ALL_PERMISSION_KEYS = [item[0] for item in PERMISSIONS]
